[package]
name = "gpui-libghostty"
description = "Native libghostty terminal component for GPUI"
version = "0.1.3"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../README.md"
build = "build.rs"
exclude = [
    "vendor/ghostty/src/crash/testdata/**",
    "vendor/ghostty/src/font/res/NotoColorEmoji.ttf",
    "vendor/ghostty/src/font/res/NotoEmoji-Regular.ttf",
    "vendor/ghostty/src/terminal/kitty/testdata/**",
]

[dependencies]
gpui.workspace = true
raw-window-handle.workspace = true

[lints.rust]
unsafe_code = "allow"
unused_must_use = "deny"

[lints.clippy]
all = { level = "deny", priority = -1 }
dbg_macro = "deny"
print_stderr = "deny"
print_stdout = "deny"
unwrap_used = "deny"
